name: austhir
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.0.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_database: ^11.3.3
  cloud_firestore: ^5.6.4
  flutter_pdfview: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/teamwork.png
    - assets/google.png
    - assets/facebook.png
    - assets/splash.png
    - assets/splash_animation.json
    - assets/animation2.json
    - assets/1.1.png
    - assets/1.2.png
    - assets/2.1.png
    - assets/2.2.png
    - assets/3.1.png
    - assets/3.2.png
    - assets/4.1.png
    - assets/4.2.png
    - assets/profile.jpg
    - assets/Advance Engineering Mathematics.pdf
    - assets/cse_seminar.jpg
    - assets/idc_summit.jpg
    - assets/pic_contest.jpg
